services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: iam-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - microservices-net

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: iam-redis
    env_file:
      - .env
    ports:
      - "${EXTERNAL_REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - microservices-net

volumes:
  order_data:

networks:
  microservices-net:
    external: true