services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: iam-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - microservices-net

  iam-server:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ../../../
      dockerfile: deploy/compose/iam/Dockerfile
    container_name: iam-server
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/config/.env:ro
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    healthcheck:
      test: [ "CMD", "/bin/grpc-health-probe", "-addr=0.0.0.0:50051" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    networks:
      - microservices-net

volumes:
  order_data:

networks:
  microservices-net:
    external: true