services:
  nginx-rtmp:
    image: alfg/nginx-rtmp:v1.6.0
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
    environment:
      STREAMING_SERVICE_IP: ${STREAMING_SERVICE_IP}
      STREAMING_SERVICE_PORT: ${STREAMING_SERVICE_PORT}
    command: >
      sh -c "envsubst '$$STREAMING_SERVICE_IP $$STREAMING_SERVICE_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx"
    restart: unless-stopped
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true